### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by louishudd** [orweinberger/bitcoin-merchant-api#9]
Just wondering if optional authentication would be useful for the api.

**Comment by orweinberger** [comment]
Currently planning on implementing an API key that will be defined in the configuration file and each route will verify the key before proceeding.

**Comment by louishudd** [comment]
That's what I was thinking, sounds good.

**Comment by orweinberger** [comment]
Done :) Thanks for opening this issue @louishudd!
